# Generated by Django 5.2.8 on 2025-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_crypto_txn_order_crypto_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, help_text='GPay / PhonePe / Paytm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_txn',
            field=models.CharField(blank=True, help_text='Simulated UPI Transaction ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card (Simulated)'), ('crypto', 'Cryptocurrency'), ('upi', 'UPI')], default='cod', max_length=20),
        ),
    ]
