# Generated by Django 5.2.8 on 2025-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_options_order_upi_app_order_upi_txn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('top', 'Top Banner'), ('card', 'Offer Card'), ('popup', 'Popup')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
