# Generated by Django 5.2.8 on 2026-01-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_payment_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded'), ('EXCHANGE_REQUESTED', 'Exchange Requested'), ('EXCHANGED', 'Exchanged')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
