# Generated by Django 5.2.8 on 2026-02-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cartitem_id_alter_category_id_alter_offerad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
